### ISSUE TITLE
Slack as Output doesn't seem to work

### ISSUE THREAD

**Issue by patcable** [graylog-labs/graylog-plugin-slack#36]
I'm trying to output messages directly to slack. When I do, I get the following stacktrace. This is with Graylog 2.1.2+50e449a. 

```
2016-12-22T21:09:37.531Z ERROR [OutputBufferProcessor] Error in output [class org.graylog2.plugins.slack.output.SlackMessageOutput].
java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
        at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_102]
        at org.graylog2.plugin.Message.getFieldAs(Message.java:380) ~[graylog.jar:?]
        at org.graylog2.plugin.Message.getTimestamp(Message.java:178) ~[graylog.jar:?]
        at org.graylog2.plugins.slack.output.SlackMessageOutput.buildMessage(SlackMessageOutput.java:97) ~[?:?]
        at org.graylog2.plugins.slack.output.SlackMessageOutput.write(SlackMessageOutput.java:67) ~[?:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor$1.run(OutputBufferProcessor.java:189) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by joschi** [comment]
@patcable The problem seems to be that the `timestamp` field is not a timestamp, but a string in your messages.

**Comment by k1-hedayati** [comment]
I had same issue, fixed `timestamp` and now it is working

**Comment by joschi** [comment]
I'm closing this issue since the original author didn't reply within 6 months.
