### ISSUE TITLE
Slack Integration issue

### ISSUE THREAD

**Issue by vady112** [graylog-labs/graylog-plugin-slack#64]
Hi I need help!! Installed and configured graylog server successfully, I am trying to set slack notification using the plugin [https://github.com/graylog-labs/graylog-plugin-slack](https://github.com/graylog-labs/graylog-plugin-slack),
But after configuring when I hit test I get 500. Here are the console log
```
client.js:802 POST http://example.gralog.org/api/alerts/callbacks/5a27efd37d3c06654a23430c/test 500 (Internal Server Error)
u._end @ client.js:802
u.end @ client.js:706
(anonymous) @ index.js:80
s @ bluebird.js:989
o._resolveFromExecutor @ bluebird.js:3246
o @ bluebird.js:2842
i.promise @ index.js:79
i.then @ index.js:121
value @ FetchProvider.js:57
(anonymous) @ FetchProvider.js:153
a @ FetchProvider.js:154
testAlert @ AlertNotificationsStore.js:61
_onTestNotification @ AlertNotification.jsx?7cee***:33
r.invokeGuardedCallback @ vendor.ab8f49e0e782eae99198.js:20
i @ vendor.ab8f49e0e782eae99198.js:20
s @ vendor.ab8f49e0e782eae99198.js:20
f @ vendor.ab8f49e0e782eae99198.js:6
m @ vendor.ab8f49e0e782eae99198.js:6
n @ vendor.ab8f49e0e782eae99198.js:20
processEventQueue @ vendor.ab8f49e0e782eae99198.js:6
n @ vendor.ab8f49e0e782eae99198.js:20
handleTopLevel @ vendor.ab8f49e0e782eae99198.js:20
a @ vendor.ab8f49e0e782eae99198.js:20
r @ vendor.ab8f49e0e782eae99198.js:20
perform @ vendor.ab8f49e0e782eae99198.js:6
batchedUpdates @ vendor.ab8f49e0e782eae99198.js:20
a @ vendor.ab8f49e0e782eae99198.js:6
dispatchEvent @ vendor.ab8f49e0e782eae99198.js:20
FetchProvider.js:17 There was an error fetching a resource: cannot POST http://example.gralog.org/api/alerts/callbacks/5a27efd37d3c06654a23430c/test (500). Additional information: Could not send message to Slack.
t @ FetchProvider.js:17
(anonymous) @ FetchProvider.js:82
i @ bluebird.js:5253
o._settlePromiseFromHandler @ bluebird.js:3275
o._settlePromise @ bluebird.js:3332
o._settlePromise0 @ bluebird.js:3377
o._settlePromises @ bluebird.js:3452
(anonymous) @ bluebird.js:175
Promise resolved (async)
o @ bluebird.js:4481
c.hasDevTools.r.settlePromises @ bluebird.js:174
o._reject @ bluebird.js:3419
o._rejectCallback @ bluebird.js:3237
(anonymous) @ bluebird.js:3249
(anonymous) @ index.js:93
u.callback @ client.js:615
(anonymous) @ client.js:434
n.emit @ index.js:133
t.onreadystatechange @ client.js:735
XMLHttpRequest.send (async)
u._end @ client.js:802
u.end @ client.js:706
(anonymous) @ index.js:80
s @ bluebird.js:989
o._resolveFromExecutor @ bluebird.js:3246
o @ bluebird.js:2842
i.promise @ index.js:79
i.then @ index.js:121
value @ FetchProvider.js:57
(anonymous) @ FetchProvider.js:153
a @ FetchProvider.js:154
testAlert @ AlertNotificationsStore.js:61
_onTestNotification @ AlertNotification.jsx?7cee***:33
r.invokeGuardedCallback @ vendor.ab8f49e0e782eae99198.js:20
i @ vendor.ab8f49e0e782eae99198.js:20
s @ vendor.ab8f49e0e782eae99198.js:20
f @ vendor.ab8f49e0e782eae99198.js:6
m @ vendor.ab8f49e0e782eae99198.js:6
n @ vendor.ab8f49e0e782eae99198.js:20
processEventQueue @ vendor.ab8f49e0e782eae99198.js:6
n @ vendor.ab8f49e0e782eae99198.js:20
handleTopLevel @ vendor.ab8f49e0e782eae99198.js:20
a @ vendor.ab8f49e0e782eae99198.js:20
r @ vendor.ab8f49e0e782eae99198.js:20
perform @ vendor.ab8f49e0e782eae99198.js:6
batchedUpdates @ vendor.ab8f49e0e782eae99198.js:20
a @ vendor.ab8f49e0e782eae99198.js:6
dispatchEvent @ vendor.ab8f49e0e782eae99198.js:20
polyfill.e83b3dfb1898222fd83b.js:1 [Violation] 'message' handler took 150ms
bluebird.js:1542 Unhandled rejection Error: cannot POST http://example.gralog.org/api/alerts/callbacks/5a27efd37d3c06654a23430c/test (500)
    at new t (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:1:2373)
    at http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:1:3774
    at i (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:72992)
    at o._settlePromiseFromHandler (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:46314)
    at o._settlePromise (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:47114)
    at o._settlePromise0 (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:47813)
    at o._settlePromises (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:49029)
    at http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:2564
    at <anonymous>
From previous event:
    at o.p [as _captureStackTrace] (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:10310)
    at o._then (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:41761)
    at o.then (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:44:40117)
    at u.i.then (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:188:117230)
    at e.value (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:1:3317)
    at http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:1:1519
    at a (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:1:1536)
    at s.testAlert (http://example.gralog.org/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.54b3d0ec48cf21479ac0.js:104:1060610)
    at t._onTestNotification (http://example.gralog.org/assets/36.e83b3dfb1898222fd83b.js:1:3134)
    at Object.r.invokeGuardedCallback (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:182385)
    at i (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:247314)
    at Object.s [as executeDispatchesInOrder] (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:247561)
    at f (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:6:34841)
    at m (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:6:34967)
    at Array.forEach (<anonymous>)
    at n (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:190321)
    at Object.processEventQueue (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:6:36254)
    at n (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:292354)
    at Object.handleTopLevel [as _handleTopLevel] (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:292426)
    at a (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:292902)
    at r (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:292716)
    at n.perform (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:6:43664)
    at Object.batchedUpdates (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:176189)
    at Object.a [as batchedUpdates] (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:6:15582)
    at dispatchEvent (http://example.gralog.org/assets/vendor.ab8f49e0e782eae99198.js:20:293785)
```

greylogserver version: Graylog 2.3.2
Plugin: version # [3.0.0](https://github.com/graylog-labs/graylog-plugin-slack/releases/tag/3.0.0)

There is nothing get logged in graylog server logs when I hit  Test. 

Here is the configuration for graylog plugin 
![graylog](https://user-images.githubusercontent.com/26999199/33711938-c7f881f6-db6b-11e7-8fee-00ec4927591a.png)

Please help

**Comment by Aenima4six2** [comment]
Your screen shot shows a webhook URI of https://hooks.slack.com/servicess/xxx. This obviously isn't correct. Did you redact the full URI or is this a typo ?

Also, something in your graylog config appears incorrect. The 500 is coming from a POST to "http://example.gralog.org/api/alerts/callbacks/5a27efd37d3c06654a23430c/test". Seems like something is trying to hit your Graylog API but is going to example.gralog.org, which is not a real domain.

**Comment by vady112** [comment]
Hi, Thank you for reply. I changed the URI of slack webhook as well as the organisation URI for posting  in real log instead of  example.graylog.org its myorganisationname.com.

Regards,

Vady

**Comment by Aenima4six2** [comment]
@vady112 This looks like a configuration issue on your end. Were you able to resolve the issue?
